### ISSUE TITLE
Importing the experiment module throws the SyntaxError below

### ISSUE THREAD

**Issue by alex-schaaf** [cgre-aachen/pynoddy#32]
Importing the experiment module throws the SyntaxError below.
Using pip-installed version of pynoddy on Ubuntu WSL 20.04.

```
import pynoddy.experiment
```

```
Traceback (most recent call last):

  File "/home/alex/miniconda3/envs/testenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-20904f32ce05>", line 10, in <module>
    import pynoddy.experiment

  File "/home/alex/miniconda3/envs/testenv/lib/python3.7/site-packages/pynoddy/experiment/__init__.py", line 19
    from . import util.sampling as Sample
                      ^
SyntaxError: invalid syntax
```

**Comment by alex-schaaf** [comment]
By the way, this does not occur if I clone and install pynoddy using `python setup.py install`

**Comment by ahinoamp** [comment]
Switch to:
from .util import sampling as Sample

to make compatible with python 3
